# Generated by Django 3.0.3 on 2021-10-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot_app', '0002_auto_20211017_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo_crypto',
            name='display_only',
        ),
    ]
