# Generated by Django 3.0.3 on 2021-10-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbot_app', '0003_remove_aboutinfo_crypto_display_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historical_Crypto',
        ),
        migrations.RemoveField(
            model_name='aboutinfo_crypto',
            name='max_order_size',
        ),
        migrations.RemoveField(
            model_name='aboutinfo_crypto',
            name='min_order_price_increment',
        ),
        migrations.RemoveField(
            model_name='aboutinfo_crypto',
            name='min_order_quantity_increment',
        ),
        migrations.RemoveField(
            model_name='aboutinfo_crypto',
            name='min_order_size',
        ),
    ]
